config/routes.rb
Rails.application.routes.draw do
  resources :foods
  resources :meals
  resources :days
  resources :diets
  resources :clients
  resources :doctors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/diet.rb
class Diet < ApplicationRecord
  belongs_to :client
  has_many :days, dependent: :destroy
end

app/controllers/diets_controller.rb
class DietsController < ApplicationController
  before_action :set_diet, only: %i[ show edit update destroy ]

  # GET /diets or /diets.json
  def index
    @diets = Diet.all
  end

  # GET /diets/1 or /diets/1.json
  def show
  end

  # GET /diets/new
  def new
    @diet = Diet.new
  end

  # GET /diets/1/edit
  def edit
  end

  # POST /diets or /diets.json
  def create
    @diet = Diet.new(diet_params)

    respond_to do |format|
      if @diet.save
        format.html { redirect_to @diet, notice: "Diet was successfully created." }
        format.json { render :show, status: :created, location: @diet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diets/1 or /diets/1.json
  def update
    respond_to do |format|
      if @diet.update(diet_params)
        format.html { redirect_to @diet, notice: "Diet was successfully updated." }
        format.json { render :show, status: :ok, location: @diet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diets/1 or /diets/1.json
  def destroy
    @diet.destroy!

    respond_to do |format|
      format.html { redirect_to diets_path, status: :see_other, notice: "Diet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diet
      @diet = Diet.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def diet_params
      params.expect(diet: [ :client_id, :start_date, :end_date, :goal ])
    end
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/views/diets/_diet.html.erb
<div id="<%= dom_id diet %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Client:</strong>
    <%= diet.client_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Start date:</strong>
    <%= diet.start_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">End date:</strong>
    <%= diet.end_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Goal:</strong>
    <%= diet.goal %>
  </p>

</div>

app/views/diets/_form.html.erb
<%= form_with(model: diet, class: "contents") do |form| %>
  <% if diet.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(diet.errors.count, "error") %> prohibited this diet from being saved:</h2>

      <ul>
        <% diet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :client_id %>
    <%= form.text_field :client_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :end_date %>
    <%= form.date_field :end_date, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :goal %>
    <%= form.text_field :goal, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/diets/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing diet</h1>

  <%= render "form", diet: @diet %>

  <%= link_to "Show this diet", @diet, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to diets", diets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/diets/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Diets" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Diets</h1>
    <%= link_to "New diet", new_diet_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="diets" class="min-w-full">
    <% @diets.each do |diet| %>
      <%= render diet %>
      <p>
        <%= link_to "Show this diet", diet, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/diets/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New diet</h1>

  <%= render "form", diet: @diet %>

  <%= link_to "Back to diets", diets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/diets/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @diet %>

    <%= link_to "Edit this diet", edit_diet_path(@diet), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to diets", diets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this diet", @diet, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>